GET http://localhost:3000

###
GET http://localhost:3000/ads

###
GET http://localhost:3000/ads/2

###
DELETE http://localhost:3000/ads/15

###
POST http://localhost:3000/ads
Content-Type: application/json

{
		"title":"Toto",
		"description":"Lorem ipsum",
		"owner":"Loic",
		"price":42,
		"createdAt":"maintenant",
		"picture":"https://imgur.com",
		"location":"Lille"
}


###
GET http://localhost:3000/tags



###
POST http://localhost:3000/newTag
Content-Type: application/json

{
		"name":"MyTag2"
}

###
GET http://localhost:3000/categories

###
POST http://localhost:3000/newCategory
Content-Type: application/json

{
		"name":"MyCategoryTest"
}

###
GET http://localhost:3000/ads?categoryId=2
